### ISSUE TITLE
Multi-language tutorials jump to beginning when language switched

### ISSUE THREAD

**Issue by marklewin** [Nexmo/station#545]
## Description

Example:

- View [websockets tutorial in default Node version](https://developer.nexmo.com/voice/voice-api/tutorials/call-a-websocket/introduction)
- Step through tasks 1-5 which are not language-specific
- In task 6, suddenly realise that you want the Python version and click on it
- Tutorial redirects to task 1

A **very minor issue and hardly high priority**, but a bit annoying 😁 

## What did you expect to happen?

When I switch language, I would expect to stay in the same task, just with a different language.

## What actually happened?

It just takes me back to the beginning of the tutorial.

## Steps to reproduce:

See description above.

**Comment by mheap** [comment]
@marklewin What happens if the task doesn't exist in the new language?

**Comment by marklewin** [comment]
@Michael Heap <m@michaelheap.com> A very good point. I've been building
tutorials where the steps co-exist, but I can see how that's not always
going to be the case.

**Comment by mheap** [comment]
@marklewin I think this is still valuable. Perhaps switch to the same item if there's a matching name, and go back to the beginning if not?

**Comment by marklewin** [comment]
Sounds good!
